[discord.mydiscord]
#You can get your token by following the instructions on
#https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
#If you want roles/groups mentions to be shown with names instead of ID,
#you'll need to give your bot the "Manage Roles" permission.
Token="${DISCORD_TOKEN}"
Server="${DISCORD_SERVER_ID}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[gitter.mygitter]
#You can get your token by going to https://developer.gitter.im/docs/welcome and SIGN I"
Token="${GIT_TOKEN}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "


#
#[[gateway]]
#    name = "reverse_gateway"
#    enable=true
#
#    [[gateway.inout]]
#    account = "gitter.mygitter"
#    channel="general"
#
#    [[gateway.inout]]
#    account ="discord.mydiscord"
#    channel = "Cheminformatics/general"

[[gateway]]
    name = "mygateway"
    enable=true

    [[gateway.inout]]
    account = "discord.mydiscord"
    channel="general"

    [[gateway.inout]]
    account ="gitter.mygitter"
    channel = "Cheminformatics/general"

